// Code generated by go-swagger; DO NOT EDIT.

package medical_expert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gircapp/api/models"
)

// DeleteExpertOKCode is the HTTP code returned for type DeleteExpertOK
const DeleteExpertOKCode int = 200

/*DeleteExpertOK successful operation

swagger:response deleteExpertOK
*/
type DeleteExpertOK struct {

	/*
	  In: Body
	*/
	Payload *models.DeleteIncidentGoodResponse `json:"body,omitempty"`
}

// NewDeleteExpertOK creates DeleteExpertOK with default headers values
func NewDeleteExpertOK() *DeleteExpertOK {

	return &DeleteExpertOK{}
}

// WithPayload adds the payload to the delete expert o k response
func (o *DeleteExpertOK) WithPayload(payload *models.DeleteIncidentGoodResponse) *DeleteExpertOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete expert o k response
func (o *DeleteExpertOK) SetPayload(payload *models.DeleteIncidentGoodResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteExpertOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
