// Code generated by go-swagger; DO NOT EDIT.

package medical_expert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// LogoutExpertHandlerFunc turns a function with the right signature into a logout expert handler
type LogoutExpertHandlerFunc func(LogoutExpertParams) middleware.Responder

// Handle executing the request and returning a response
func (fn LogoutExpertHandlerFunc) Handle(params LogoutExpertParams) middleware.Responder {
	return fn(params)
}

// LogoutExpertHandler interface for that can handle valid logout expert params
type LogoutExpertHandler interface {
	Handle(LogoutExpertParams) middleware.Responder
}

// NewLogoutExpert creates a new http.Handler for the logout expert operation
func NewLogoutExpert(ctx *middleware.Context, handler LogoutExpertHandler) *LogoutExpert {
	return &LogoutExpert{Context: ctx, Handler: handler}
}

/* LogoutExpert swagger:route GET /v3/expert/logout Medical Expert logoutExpert

login expert

Use this tto login an expert

*/
type LogoutExpert struct {
	Context *middleware.Context
	Handler LogoutExpertHandler
}

func (o *LogoutExpert) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewLogoutExpertParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
