// Code generated by go-swagger; DO NOT EDIT.

package medical_expert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gircapp/api/models"
)

// LogoutExpertOKCode is the HTTP code returned for type LogoutExpertOK
const LogoutExpertOKCode int = 200

/*LogoutExpertOK successful operation

swagger:response logoutExpertOK
*/
type LogoutExpertOK struct {

	/*
	  In: Body
	*/
	Payload *models.DeleteIncidentGoodResponse `json:"body,omitempty"`
}

// NewLogoutExpertOK creates LogoutExpertOK with default headers values
func NewLogoutExpertOK() *LogoutExpertOK {

	return &LogoutExpertOK{}
}

// WithPayload adds the payload to the logout expert o k response
func (o *LogoutExpertOK) WithPayload(payload *models.DeleteIncidentGoodResponse) *LogoutExpertOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the logout expert o k response
func (o *LogoutExpertOK) SetPayload(payload *models.DeleteIncidentGoodResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogoutExpertOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// LogoutExpertUnauthorizedCode is the HTTP code returned for type LogoutExpertUnauthorized
const LogoutExpertUnauthorizedCode int = 401

/*LogoutExpertUnauthorized bad authorization token

swagger:response logoutExpertUnauthorized
*/
type LogoutExpertUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.UpdateIncidentIncidentIDNotFoundResponse `json:"body,omitempty"`
}

// NewLogoutExpertUnauthorized creates LogoutExpertUnauthorized with default headers values
func NewLogoutExpertUnauthorized() *LogoutExpertUnauthorized {

	return &LogoutExpertUnauthorized{}
}

// WithPayload adds the payload to the logout expert unauthorized response
func (o *LogoutExpertUnauthorized) WithPayload(payload *models.UpdateIncidentIncidentIDNotFoundResponse) *LogoutExpertUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the logout expert unauthorized response
func (o *LogoutExpertUnauthorized) SetPayload(payload *models.UpdateIncidentIncidentIDNotFoundResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogoutExpertUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// LogoutExpertNotFoundCode is the HTTP code returned for type LogoutExpertNotFound
const LogoutExpertNotFoundCode int = 404

/*LogoutExpertNotFound incident not found

swagger:response logoutExpertNotFound
*/
type LogoutExpertNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.DeleteIncidentIncidentIDNotFoundResponse `json:"body,omitempty"`
}

// NewLogoutExpertNotFound creates LogoutExpertNotFound with default headers values
func NewLogoutExpertNotFound() *LogoutExpertNotFound {

	return &LogoutExpertNotFound{}
}

// WithPayload adds the payload to the logout expert not found response
func (o *LogoutExpertNotFound) WithPayload(payload *models.DeleteIncidentIncidentIDNotFoundResponse) *LogoutExpertNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the logout expert not found response
func (o *LogoutExpertNotFound) SetPayload(payload *models.DeleteIncidentIncidentIDNotFoundResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LogoutExpertNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
