// Code generated by go-swagger; DO NOT EDIT.

package medical_expert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gircapp/api/models"
)

// UpdateExpertOKCode is the HTTP code returned for type UpdateExpertOK
const UpdateExpertOKCode int = 200

/*UpdateExpertOK successful operation

swagger:response updateExpertOK
*/
type UpdateExpertOK struct {

	/*
	  In: Body
	*/
	Payload *models.DeleteIncidentGoodResponse `json:"body,omitempty"`
}

// NewUpdateExpertOK creates UpdateExpertOK with default headers values
func NewUpdateExpertOK() *UpdateExpertOK {

	return &UpdateExpertOK{}
}

// WithPayload adds the payload to the update expert o k response
func (o *UpdateExpertOK) WithPayload(payload *models.DeleteIncidentGoodResponse) *UpdateExpertOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update expert o k response
func (o *UpdateExpertOK) SetPayload(payload *models.DeleteIncidentGoodResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateExpertOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
