// Code generated by go-swagger; DO NOT EDIT.

package e_r_p_incident

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateERPIncidentHandlerFunc turns a function with the right signature into a create e r p incident handler
type CreateERPIncidentHandlerFunc func(CreateERPIncidentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateERPIncidentHandlerFunc) Handle(params CreateERPIncidentParams) middleware.Responder {
	return fn(params)
}

// CreateERPIncidentHandler interface for that can handle valid create e r p incident params
type CreateERPIncidentHandler interface {
	Handle(CreateERPIncidentParams) middleware.Responder
}

// NewCreateERPIncident creates a new http.Handler for the create e r p incident operation
func NewCreateERPIncident(ctx *middleware.Context, handler CreateERPIncidentHandler) *CreateERPIncident {
	return &CreateERPIncident{Context: ctx, Handler: handler}
}

/* CreateERPIncident swagger:route POST /v3/erpincident ERP Incident createERPIncident

create create Emergency Room Physician incident

Use this to delete an incident by incidentId

*/
type CreateERPIncident struct {
	Context *middleware.Context
	Handler CreateERPIncidentHandler
}

func (o *CreateERPIncident) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateERPIncidentParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
