// Code generated by go-swagger; DO NOT EDIT.

// Package restapi GIRC App API
//
//  This is test server for GIRC app
//  Schemes:
//    https
//  Host: girc.app
//  BasePath: /v2
//  Version: 2.0.0
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
