// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is test server for GIRC app",
    "title": "GIRC App API",
    "version": "2.0.0"
  },
  "host": "girc.app",
  "basePath": "/v2",
  "paths": {
    "/incident": {
      "get": {
        "description": "Use this to get all incidents created by a user. incidents are listed in array in order from newest to oldest created",
        "produces": [
          "application/json"
        ],
        "tags": [
          "incident"
        ],
        "summary": "Get incidents",
        "operationId": "getIncidents",
        "parameters": [
          {
            "type": "string",
            "description": "authorization header contains bearer token",
            "name": "Authorization",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/GetIncidentsGoodResponse"
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/GetIncidentsBadRequestResponse"
            }
          },
          "404": {
            "description": "userid not found",
            "schema": {
              "$ref": "#/definitions/GetIncidentsUserIdNotFoundResponse"
            }
          }
        }
      },
      "post": {
        "description": "use this to create an incident for a userId",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "incident"
        ],
        "summary": "Create an incident",
        "operationId": "createIncident",
        "parameters": [
          {
            "type": "string",
            "description": "authorization header contains bearer token",
            "name": "Authorization",
            "in": "header",
            "required": true
          },
          {
            "name": "incident",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateIncident"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation, only returns token if not using OAuth",
            "schema": {
              "$ref": "#/definitions/CreateIncidentGoodResponse"
            },
            "headers": {
              "Authentication": {
                "type": "string",
                "description": "token"
              }
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/CreateIncidentInvalidIncidentResponse"
            }
          },
          "404": {
            "description": "userId for this incident is not found",
            "schema": {
              "$ref": "#/definitions/CreateIncidentUserIdNotFoundResponse"
            }
          }
        }
      },
      "delete": {
        "description": "Use this to delete an incident by incidentId",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "incident"
        ],
        "summary": "Delete incident",
        "operationId": "deleteIncidents",
        "parameters": [
          {
            "type": "string",
            "description": "authorization header contains bearer token",
            "name": "Authorization",
            "in": "header",
            "required": true
          },
          {
            "name": "incident",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/DeleteIncident"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/DeleteIncidentGoodResponse"
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/UpdateIncidentIncidentIdNotFoundResponse"
            }
          },
          "404": {
            "description": "incident not found",
            "schema": {
              "$ref": "#/definitions/DeleteIncidentIncidentIdNotFoundResponse"
            }
          }
        }
      },
      "patch": {
        "description": "Use this to update an incident by incidentId. Only fields with non-empty strings are updated. If a field is not to be updated, set the value to equal an empty string",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "incident"
        ],
        "summary": "Update incident",
        "operationId": "updateIncidents",
        "parameters": [
          {
            "type": "string",
            "description": "authorization header contains bearer token",
            "name": "Authorization",
            "in": "header",
            "required": true
          },
          {
            "name": "incident",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateIncident"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/UpdateIncidentGoodResponse"
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/UpdateIncidentIncidentIdNotFoundResponse"
            }
          },
          "404": {
            "description": "incident not found",
            "schema": {
              "$ref": "#/definitions/UpdateIncidentIncidentIdNotFoundResponse"
            }
          }
        }
      }
    },
    "/user": {
      "get": {
        "description": "Get a user's information.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Get user's information.",
        "operationId": "getUser",
        "parameters": [
          {
            "type": "string",
            "description": "authorization header contains bearer token",
            "name": "Authorization",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/GetUserGoodResponse"
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/GetUserBadResponse"
            }
          },
          "404": {
            "description": "user not found",
            "schema": {
              "$ref": "#/definitions/GetUserBadResponse"
            }
          }
        }
      },
      "post": {
        "description": "register a user with his information",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "register a user",
        "operationId": "createUser",
        "parameters": [
          {
            "type": "string",
            "description": "authorization header contains bearer token",
            "name": "Authorization",
            "in": "header",
            "required": true
          },
          {
            "description": "a user's information",
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateUser"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/CreateUserGoodResponse"
            }
          },
          "400": {
            "description": "database error while creating user",
            "schema": {
              "$ref": "#/definitions/CreateUserBadResponse"
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/CreateUserBadResponse"
            }
          }
        }
      },
      "delete": {
        "description": "deletes a user",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "unregisters a user, for testing only will be removed in production",
        "operationId": "deleteUser",
        "parameters": [
          {
            "type": "string",
            "description": "authorization token",
            "name": "Authorization",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/DeleteUserGoodResponse"
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/DeleteUserBadResponse"
            }
          },
          "404": {
            "description": "user with requested userid not found",
            "schema": {
              "$ref": "#/definitions/DeleteUserBadResponse"
            }
          }
        }
      },
      "patch": {
        "description": "Update a user's info",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Update user",
        "operationId": "updateUser",
        "parameters": [
          {
            "type": "string",
            "description": "authorization header contains bearer token",
            "name": "Authorization",
            "in": "header",
            "required": true
          },
          {
            "description": "Only fields with non-empty strings are updated. If a field is not to be updated, set the value to equal an empty string",
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateUser"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/UpdateUserGoodResponse"
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/UpdateUserInvalidResponse"
            }
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/UpdateUserNotFoundResponse"
            }
          }
        }
      }
    },
    "/verify": {
      "patch": {
        "description": "verified field is true to verify, false to unverify",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "verify"
        ],
        "summary": "use this to verify or unverify a user, for testing only",
        "operationId": "verify",
        "parameters": [
          {
            "type": "string",
            "description": "authorization header contains bearer token",
            "name": "Authorization",
            "in": "header",
            "required": true
          },
          {
            "description": "verified field is true to verify, false to unverify",
            "name": "verified",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Verify"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/UpdateUserGoodResponse"
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/UpdateUserNotFoundResponse"
            }
          },
          "404": {
            "description": "userid not found",
            "schema": {
              "$ref": "#/definitions/UpdateUserNotFoundResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CreateExpert": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Degree": {
          "type": "number"
        },
        "Email": {
          "type": "string"
        },
        "Expertise": {
          "type": "number"
        },
        "ID": {
          "type": "string"
        },
        "Password": {
          "type": "string"
        },
        "Verified": {
          "type": "boolean"
        }
      }
    },
    "CreateIncident": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Anterior": {
          "type": "string"
        },
        "Approximate_Patient_Age": {
          "type": "string"
        },
        "Date_of_Incident": {
          "type": "string"
        },
        "Gender": {
          "type": "string"
        },
        "ID": {
          "type": "string"
        },
        "Incident_Description": {
          "type": "string"
        },
        "Largest_Length": {
          "type": "string"
        },
        "Location_of_object": {
          "type": "string"
        },
        "Long-term_prognosis": {
          "type": "string"
        },
        "Object_Basic_Shape": {
          "type": "string"
        },
        "Object_Consistency": {
          "type": "string"
        },
        "The_object_is": {
          "type": "string"
        },
        "What_material_is_the_object_made_of": {
          "type": "string"
        }
      }
    },
    "CreateIncidentGoodResponse": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Anterior": {
          "type": "string"
        },
        "Approximate_Patient_Age": {
          "type": "string"
        },
        "Created": {
          "type": "boolean"
        },
        "Date_of_Incident": {
          "type": "string"
        },
        "Gender": {
          "type": "string"
        },
        "ID": {
          "type": "string"
        },
        "Incident_Description": {
          "type": "string"
        },
        "Largest_Length": {
          "type": "string"
        },
        "Location_of_object": {
          "type": "string"
        },
        "Long-term_prognosis": {
          "type": "string"
        },
        "Object_Basic_Shape": {
          "type": "string"
        },
        "Object_Consistency": {
          "type": "string"
        },
        "The_object_is": {
          "type": "string"
        },
        "UserID": {
          "type": "string"
        },
        "What_material_is_the_object_made_of": {
          "type": "string"
        }
      }
    },
    "CreateIncidentInvalidIncidentResponse": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Anterior": {
          "type": "string"
        },
        "Approximate_Patient_Age": {
          "type": "string"
        },
        "Created": {
          "type": "boolean",
          "default": false
        },
        "Date_of_Incident": {
          "type": "string"
        },
        "Gender": {
          "type": "string"
        },
        "ID": {
          "type": "string"
        },
        "Incident_Description": {
          "type": "string"
        },
        "Largest_Length": {
          "type": "string"
        },
        "Location_of_object": {
          "type": "string"
        },
        "Long-term_prognosis": {
          "type": "string"
        },
        "Object_Basic_Shape": {
          "type": "string"
        },
        "Object_Consistency": {
          "type": "string"
        },
        "The_object_is": {
          "type": "string"
        },
        "What_material_is_the_object_made_of": {
          "type": "string"
        }
      }
    },
    "CreateIncidentUserIdNotFoundResponse": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Anterior": {
          "type": "string"
        },
        "Approximate_Patient_Age": {
          "type": "string"
        },
        "Created": {
          "type": "boolean",
          "default": false
        },
        "Date_of_Incident": {
          "type": "string"
        },
        "Gender": {
          "type": "string"
        },
        "ID": {
          "type": "string"
        },
        "Incident_Description": {
          "type": "string"
        },
        "Largest_Length": {
          "type": "string"
        },
        "Location_of_object": {
          "type": "string"
        },
        "Long-term_prognosis": {
          "type": "string"
        },
        "Object_Basic_Shape": {
          "type": "string"
        },
        "Object_Consistency": {
          "type": "string"
        },
        "The_object_is": {
          "type": "string"
        },
        "What_material_is_the_object_made_of": {
          "type": "string"
        }
      }
    },
    "CreateUser": {
      "type": "object",
      "required": [
        "name",
        "email",
        "degree",
        "specialty"
      ],
      "properties": {
        "degree": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "specialty": {
          "type": "string"
        }
      }
    },
    "CreateUserBadResponse": {
      "type": "object",
      "required": [
        "created",
        "name",
        "email",
        "specialty",
        "degree"
      ],
      "properties": {
        "created": {
          "type": "boolean",
          "example": false
        },
        "degree": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "specialty": {
          "type": "string"
        }
      }
    },
    "CreateUserGoodResponse": {
      "type": "object",
      "required": [
        "userId",
        "created"
      ],
      "properties": {
        "created": {
          "type": "boolean"
        },
        "degree": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "specialty": {
          "type": "string"
        },
        "userId": {
          "type": "string"
        }
      }
    },
    "DeleteIncident": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "ID": {
          "type": "string"
        }
      }
    },
    "DeleteIncidentGoodResponse": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Deleted": {
          "type": "boolean",
          "default": true
        },
        "ID": {
          "type": "string"
        }
      }
    },
    "DeleteIncidentIncidentIdNotFoundResponse": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Deleted": {
          "type": "boolean",
          "default": true
        },
        "ID": {
          "type": "string"
        }
      }
    },
    "DeleteUserBadResponse": {
      "type": "object",
      "required": [
        "userId",
        "deleted"
      ],
      "properties": {
        "deleted": {
          "type": "boolean",
          "example": false
        },
        "userId": {
          "type": "string"
        }
      }
    },
    "DeleteUserGoodResponse": {
      "type": "object",
      "required": [
        "deleted"
      ],
      "properties": {
        "deleted": {
          "type": "boolean"
        },
        "userId": {
          "type": "string"
        }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "GetExpertResponse": {
      "type": "object",
      "properties": {
        "Degree": {
          "type": "number"
        },
        "Email": {
          "type": "string"
        },
        "Expertise": {
          "type": "number"
        },
        "ID": {
          "type": "string"
        },
        "Password": {
          "type": "string"
        },
        "Verified": {
          "type": "boolean"
        }
      }
    },
    "GetIncidentsBadRequestResponse": {
      "type": "object",
      "required": [
        "userId"
      ],
      "properties": {
        "userId": {
          "type": "string"
        }
      }
    },
    "GetIncidentsGoodResponse": {
      "type": "object",
      "required": [
        "UserID"
      ],
      "properties": {
        "Incidents": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GetIncidentsIncident"
          }
        },
        "UserID": {
          "type": "string"
        }
      }
    },
    "GetIncidentsIncident": {
      "type": "object",
      "properties": {
        "Anterior": {
          "type": "string"
        },
        "Approximate_Patient_Age": {
          "type": "string"
        },
        "Date_of_Incident": {
          "type": "string"
        },
        "Gender": {
          "type": "string"
        },
        "ID": {
          "type": "string"
        },
        "Incident_Description": {
          "type": "string"
        },
        "Largest_Length": {
          "type": "string"
        },
        "Location_of_object": {
          "type": "string"
        },
        "Long-term_prognosis": {
          "type": "string"
        },
        "Object_Basic_Shape": {
          "type": "string"
        },
        "Object_Consistency": {
          "type": "string"
        },
        "The_object_is": {
          "type": "string"
        },
        "What_material_is_the_object_made_of": {
          "type": "string"
        }
      }
    },
    "GetIncidentsUserIdNotFoundResponse": {
      "type": "object",
      "required": [
        "userId"
      ],
      "properties": {
        "userId": {
          "type": "string"
        }
      }
    },
    "GetUserBadResponse": {
      "type": "object",
      "required": [
        "userId"
      ],
      "properties": {
        "userId": {
          "type": "string"
        }
      }
    },
    "GetUserGoodResponse": {
      "type": "object",
      "required": [
        "userId",
        "verified",
        "name",
        "degree",
        "specialty",
        "email"
      ],
      "properties": {
        "degree": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "specialty": {
          "type": "string"
        },
        "userId": {
          "type": "string"
        },
        "verified": {
          "type": "boolean",
          "example": false
        }
      }
    },
    "UpdateIncident": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Anterior": {
          "type": "string"
        },
        "Approximate_Patient_Age": {
          "type": "string"
        },
        "Date_of_Incident": {
          "type": "string"
        },
        "Gender": {
          "type": "string"
        },
        "ID": {
          "type": "string"
        },
        "Incident_Description": {
          "type": "string"
        },
        "Largest_Length": {
          "type": "string"
        },
        "Location_of_object": {
          "type": "string"
        },
        "Long-term_prognosis": {
          "type": "string"
        },
        "Object_Basic_Shape": {
          "type": "string"
        },
        "Object_Consistency": {
          "type": "string"
        },
        "The_object_is": {
          "type": "string"
        },
        "What_material_is_the_object_made_of": {
          "type": "string"
        }
      }
    },
    "UpdateIncidentGoodResponse": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Anterior": {
          "type": "string"
        },
        "Approximate_Patient_Age": {
          "type": "string"
        },
        "Date_of_Incident": {
          "type": "string"
        },
        "Gender": {
          "type": "string"
        },
        "ID": {
          "type": "string"
        },
        "Incident_Description": {
          "type": "string"
        },
        "Largest_Length": {
          "type": "string"
        },
        "Location_of_object": {
          "type": "string"
        },
        "Long-term_prognosis": {
          "type": "string"
        },
        "Object_Basic_Shape": {
          "type": "string"
        },
        "Object_Consistency": {
          "type": "string"
        },
        "The_object_is": {
          "type": "string"
        },
        "Updated": {
          "type": "boolean",
          "default": true
        },
        "What_material_is_the_object_made_of": {
          "type": "string"
        }
      }
    },
    "UpdateIncidentIncidentIdNotFoundResponse": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Anterior": {
          "type": "string"
        },
        "Approximate_Patient_Age": {
          "type": "string"
        },
        "Date_of_Incident": {
          "type": "string"
        },
        "Gender": {
          "type": "string"
        },
        "ID": {
          "type": "string"
        },
        "Incident_Description": {
          "type": "string"
        },
        "Largest_Length": {
          "type": "string"
        },
        "Location_of_object": {
          "type": "string"
        },
        "Long-term_prognosis": {
          "type": "string"
        },
        "Object_Basic_Shape": {
          "type": "string"
        },
        "Object_Consistency": {
          "type": "string"
        },
        "The_object_is": {
          "type": "string"
        },
        "Updated": {
          "type": "boolean",
          "default": false
        },
        "What_material_is_the_object_made_of": {
          "type": "string"
        }
      }
    },
    "UpdateUser": {
      "type": "object",
      "properties": {
        "degree": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "specialty": {
          "type": "string"
        }
      }
    },
    "UpdateUserGoodResponse": {
      "type": "object",
      "required": [
        "userId",
        "verified",
        "name",
        "degree",
        "updated",
        "email",
        "specialty"
      ],
      "properties": {
        "degree": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "specialty": {
          "type": "string"
        },
        "updated": {
          "type": "boolean"
        },
        "userId": {
          "type": "string"
        },
        "verified": {
          "type": "boolean",
          "default": false
        }
      }
    },
    "UpdateUserInvalidResponse": {
      "type": "object",
      "required": [
        "verified",
        "name",
        "degree",
        "specialty",
        "updated",
        "email"
      ],
      "properties": {
        "degree": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "specialty": {
          "type": "string"
        },
        "updated": {
          "type": "boolean",
          "example": false
        },
        "verified": {
          "type": "boolean",
          "example": false
        }
      }
    },
    "UpdateUserNotFoundResponse": {
      "type": "object",
      "required": [
        "userId"
      ],
      "properties": {
        "updated": {
          "type": "boolean",
          "default": false
        },
        "userId": {
          "type": "string"
        }
      }
    },
    "Verify": {
      "type": "object",
      "required": [
        "verified"
      ],
      "properties": {
        "verified": {
          "type": "boolean"
        }
      }
    }
  },
  "tags": [
    {
      "description": "to create, update, and delete incidents",
      "name": "incident"
    },
    {
      "description": "for user registration and authentication",
      "name": "user"
    },
    {
      "description": "only used for testing and will be removed in production",
      "name": "verify"
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "This is test server for GIRC app",
    "title": "GIRC App API",
    "version": "2.0.0"
  },
  "host": "girc.app",
  "basePath": "/v2",
  "paths": {
    "/incident": {
      "get": {
        "description": "Use this to get all incidents created by a user. incidents are listed in array in order from newest to oldest created",
        "produces": [
          "application/json"
        ],
        "tags": [
          "incident"
        ],
        "summary": "Get incidents",
        "operationId": "getIncidents",
        "parameters": [
          {
            "type": "string",
            "description": "authorization header contains bearer token",
            "name": "Authorization",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/GetIncidentsGoodResponse"
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/GetIncidentsBadRequestResponse"
            }
          },
          "404": {
            "description": "userid not found",
            "schema": {
              "$ref": "#/definitions/GetIncidentsUserIdNotFoundResponse"
            }
          }
        }
      },
      "post": {
        "description": "use this to create an incident for a userId",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "incident"
        ],
        "summary": "Create an incident",
        "operationId": "createIncident",
        "parameters": [
          {
            "type": "string",
            "description": "authorization header contains bearer token",
            "name": "Authorization",
            "in": "header",
            "required": true
          },
          {
            "name": "incident",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateIncident"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation, only returns token if not using OAuth",
            "schema": {
              "$ref": "#/definitions/CreateIncidentGoodResponse"
            },
            "headers": {
              "Authentication": {
                "type": "string",
                "description": "token"
              }
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/CreateIncidentInvalidIncidentResponse"
            }
          },
          "404": {
            "description": "userId for this incident is not found",
            "schema": {
              "$ref": "#/definitions/CreateIncidentUserIdNotFoundResponse"
            }
          }
        }
      },
      "delete": {
        "description": "Use this to delete an incident by incidentId",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "incident"
        ],
        "summary": "Delete incident",
        "operationId": "deleteIncidents",
        "parameters": [
          {
            "type": "string",
            "description": "authorization header contains bearer token",
            "name": "Authorization",
            "in": "header",
            "required": true
          },
          {
            "name": "incident",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/DeleteIncident"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/DeleteIncidentGoodResponse"
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/UpdateIncidentIncidentIdNotFoundResponse"
            }
          },
          "404": {
            "description": "incident not found",
            "schema": {
              "$ref": "#/definitions/DeleteIncidentIncidentIdNotFoundResponse"
            }
          }
        }
      },
      "patch": {
        "description": "Use this to update an incident by incidentId. Only fields with non-empty strings are updated. If a field is not to be updated, set the value to equal an empty string",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "incident"
        ],
        "summary": "Update incident",
        "operationId": "updateIncidents",
        "parameters": [
          {
            "type": "string",
            "description": "authorization header contains bearer token",
            "name": "Authorization",
            "in": "header",
            "required": true
          },
          {
            "name": "incident",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateIncident"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/UpdateIncidentGoodResponse"
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/UpdateIncidentIncidentIdNotFoundResponse"
            }
          },
          "404": {
            "description": "incident not found",
            "schema": {
              "$ref": "#/definitions/UpdateIncidentIncidentIdNotFoundResponse"
            }
          }
        }
      }
    },
    "/user": {
      "get": {
        "description": "Get a user's information.",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Get user's information.",
        "operationId": "getUser",
        "parameters": [
          {
            "type": "string",
            "description": "authorization header contains bearer token",
            "name": "Authorization",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/GetUserGoodResponse"
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/GetUserBadResponse"
            }
          },
          "404": {
            "description": "user not found",
            "schema": {
              "$ref": "#/definitions/GetUserBadResponse"
            }
          }
        }
      },
      "post": {
        "description": "register a user with his information",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "register a user",
        "operationId": "createUser",
        "parameters": [
          {
            "type": "string",
            "description": "authorization header contains bearer token",
            "name": "Authorization",
            "in": "header",
            "required": true
          },
          {
            "description": "a user's information",
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/CreateUser"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/CreateUserGoodResponse"
            }
          },
          "400": {
            "description": "database error while creating user",
            "schema": {
              "$ref": "#/definitions/CreateUserBadResponse"
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/CreateUserBadResponse"
            }
          }
        }
      },
      "delete": {
        "description": "deletes a user",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "unregisters a user, for testing only will be removed in production",
        "operationId": "deleteUser",
        "parameters": [
          {
            "type": "string",
            "description": "authorization token",
            "name": "Authorization",
            "in": "header",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/DeleteUserGoodResponse"
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/DeleteUserBadResponse"
            }
          },
          "404": {
            "description": "user with requested userid not found",
            "schema": {
              "$ref": "#/definitions/DeleteUserBadResponse"
            }
          }
        }
      },
      "patch": {
        "description": "Update a user's info",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "user"
        ],
        "summary": "Update user",
        "operationId": "updateUser",
        "parameters": [
          {
            "type": "string",
            "description": "authorization header contains bearer token",
            "name": "Authorization",
            "in": "header",
            "required": true
          },
          {
            "description": "Only fields with non-empty strings are updated. If a field is not to be updated, set the value to equal an empty string",
            "name": "user",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/UpdateUser"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/UpdateUserGoodResponse"
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/UpdateUserInvalidResponse"
            }
          },
          "404": {
            "description": "User not found",
            "schema": {
              "$ref": "#/definitions/UpdateUserNotFoundResponse"
            }
          }
        }
      }
    },
    "/verify": {
      "patch": {
        "description": "verified field is true to verify, false to unverify",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "verify"
        ],
        "summary": "use this to verify or unverify a user, for testing only",
        "operationId": "verify",
        "parameters": [
          {
            "type": "string",
            "description": "authorization header contains bearer token",
            "name": "Authorization",
            "in": "header",
            "required": true
          },
          {
            "description": "verified field is true to verify, false to unverify",
            "name": "verified",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Verify"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful operation",
            "schema": {
              "$ref": "#/definitions/UpdateUserGoodResponse"
            }
          },
          "401": {
            "description": "bad authorization token",
            "schema": {
              "$ref": "#/definitions/UpdateUserNotFoundResponse"
            }
          },
          "404": {
            "description": "userid not found",
            "schema": {
              "$ref": "#/definitions/UpdateUserNotFoundResponse"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "CreateExpert": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Degree": {
          "type": "number"
        },
        "Email": {
          "type": "string"
        },
        "Expertise": {
          "type": "number"
        },
        "ID": {
          "type": "string"
        },
        "Password": {
          "type": "string"
        },
        "Verified": {
          "type": "boolean"
        }
      }
    },
    "CreateIncident": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Anterior": {
          "type": "string"
        },
        "Approximate_Patient_Age": {
          "type": "string"
        },
        "Date_of_Incident": {
          "type": "string"
        },
        "Gender": {
          "type": "string"
        },
        "ID": {
          "type": "string"
        },
        "Incident_Description": {
          "type": "string"
        },
        "Largest_Length": {
          "type": "string"
        },
        "Location_of_object": {
          "type": "string"
        },
        "Long-term_prognosis": {
          "type": "string"
        },
        "Object_Basic_Shape": {
          "type": "string"
        },
        "Object_Consistency": {
          "type": "string"
        },
        "The_object_is": {
          "type": "string"
        },
        "What_material_is_the_object_made_of": {
          "type": "string"
        }
      }
    },
    "CreateIncidentGoodResponse": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Anterior": {
          "type": "string"
        },
        "Approximate_Patient_Age": {
          "type": "string"
        },
        "Created": {
          "type": "boolean"
        },
        "Date_of_Incident": {
          "type": "string"
        },
        "Gender": {
          "type": "string"
        },
        "ID": {
          "type": "string"
        },
        "Incident_Description": {
          "type": "string"
        },
        "Largest_Length": {
          "type": "string"
        },
        "Location_of_object": {
          "type": "string"
        },
        "Long-term_prognosis": {
          "type": "string"
        },
        "Object_Basic_Shape": {
          "type": "string"
        },
        "Object_Consistency": {
          "type": "string"
        },
        "The_object_is": {
          "type": "string"
        },
        "UserID": {
          "type": "string"
        },
        "What_material_is_the_object_made_of": {
          "type": "string"
        }
      }
    },
    "CreateIncidentInvalidIncidentResponse": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Anterior": {
          "type": "string"
        },
        "Approximate_Patient_Age": {
          "type": "string"
        },
        "Created": {
          "type": "boolean",
          "default": false
        },
        "Date_of_Incident": {
          "type": "string"
        },
        "Gender": {
          "type": "string"
        },
        "ID": {
          "type": "string"
        },
        "Incident_Description": {
          "type": "string"
        },
        "Largest_Length": {
          "type": "string"
        },
        "Location_of_object": {
          "type": "string"
        },
        "Long-term_prognosis": {
          "type": "string"
        },
        "Object_Basic_Shape": {
          "type": "string"
        },
        "Object_Consistency": {
          "type": "string"
        },
        "The_object_is": {
          "type": "string"
        },
        "What_material_is_the_object_made_of": {
          "type": "string"
        }
      }
    },
    "CreateIncidentUserIdNotFoundResponse": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Anterior": {
          "type": "string"
        },
        "Approximate_Patient_Age": {
          "type": "string"
        },
        "Created": {
          "type": "boolean",
          "default": false
        },
        "Date_of_Incident": {
          "type": "string"
        },
        "Gender": {
          "type": "string"
        },
        "ID": {
          "type": "string"
        },
        "Incident_Description": {
          "type": "string"
        },
        "Largest_Length": {
          "type": "string"
        },
        "Location_of_object": {
          "type": "string"
        },
        "Long-term_prognosis": {
          "type": "string"
        },
        "Object_Basic_Shape": {
          "type": "string"
        },
        "Object_Consistency": {
          "type": "string"
        },
        "The_object_is": {
          "type": "string"
        },
        "What_material_is_the_object_made_of": {
          "type": "string"
        }
      }
    },
    "CreateUser": {
      "type": "object",
      "required": [
        "name",
        "email",
        "degree",
        "specialty"
      ],
      "properties": {
        "degree": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "specialty": {
          "type": "string"
        }
      }
    },
    "CreateUserBadResponse": {
      "type": "object",
      "required": [
        "created",
        "name",
        "email",
        "specialty",
        "degree"
      ],
      "properties": {
        "created": {
          "type": "boolean",
          "example": false
        },
        "degree": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "specialty": {
          "type": "string"
        }
      }
    },
    "CreateUserGoodResponse": {
      "type": "object",
      "required": [
        "userId",
        "created"
      ],
      "properties": {
        "created": {
          "type": "boolean"
        },
        "degree": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "specialty": {
          "type": "string"
        },
        "userId": {
          "type": "string"
        }
      }
    },
    "DeleteIncident": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "ID": {
          "type": "string"
        }
      }
    },
    "DeleteIncidentGoodResponse": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Deleted": {
          "type": "boolean",
          "default": true
        },
        "ID": {
          "type": "string"
        }
      }
    },
    "DeleteIncidentIncidentIdNotFoundResponse": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Deleted": {
          "type": "boolean",
          "default": true
        },
        "ID": {
          "type": "string"
        }
      }
    },
    "DeleteUserBadResponse": {
      "type": "object",
      "required": [
        "userId",
        "deleted"
      ],
      "properties": {
        "deleted": {
          "type": "boolean",
          "example": false
        },
        "userId": {
          "type": "string"
        }
      }
    },
    "DeleteUserGoodResponse": {
      "type": "object",
      "required": [
        "deleted"
      ],
      "properties": {
        "deleted": {
          "type": "boolean"
        },
        "userId": {
          "type": "string"
        }
      }
    },
    "ErrorResponse": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        }
      }
    },
    "GetExpertResponse": {
      "type": "object",
      "properties": {
        "Degree": {
          "type": "number"
        },
        "Email": {
          "type": "string"
        },
        "Expertise": {
          "type": "number"
        },
        "ID": {
          "type": "string"
        },
        "Password": {
          "type": "string"
        },
        "Verified": {
          "type": "boolean"
        }
      }
    },
    "GetIncidentsBadRequestResponse": {
      "type": "object",
      "required": [
        "userId"
      ],
      "properties": {
        "userId": {
          "type": "string"
        }
      }
    },
    "GetIncidentsGoodResponse": {
      "type": "object",
      "required": [
        "UserID"
      ],
      "properties": {
        "Incidents": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GetIncidentsIncident"
          }
        },
        "UserID": {
          "type": "string"
        }
      }
    },
    "GetIncidentsIncident": {
      "type": "object",
      "properties": {
        "Anterior": {
          "type": "string"
        },
        "Approximate_Patient_Age": {
          "type": "string"
        },
        "Date_of_Incident": {
          "type": "string"
        },
        "Gender": {
          "type": "string"
        },
        "ID": {
          "type": "string"
        },
        "Incident_Description": {
          "type": "string"
        },
        "Largest_Length": {
          "type": "string"
        },
        "Location_of_object": {
          "type": "string"
        },
        "Long-term_prognosis": {
          "type": "string"
        },
        "Object_Basic_Shape": {
          "type": "string"
        },
        "Object_Consistency": {
          "type": "string"
        },
        "The_object_is": {
          "type": "string"
        },
        "What_material_is_the_object_made_of": {
          "type": "string"
        }
      }
    },
    "GetIncidentsUserIdNotFoundResponse": {
      "type": "object",
      "required": [
        "userId"
      ],
      "properties": {
        "userId": {
          "type": "string"
        }
      }
    },
    "GetUserBadResponse": {
      "type": "object",
      "required": [
        "userId"
      ],
      "properties": {
        "userId": {
          "type": "string"
        }
      }
    },
    "GetUserGoodResponse": {
      "type": "object",
      "required": [
        "userId",
        "verified",
        "name",
        "degree",
        "specialty",
        "email"
      ],
      "properties": {
        "degree": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "specialty": {
          "type": "string"
        },
        "userId": {
          "type": "string"
        },
        "verified": {
          "type": "boolean",
          "example": false
        }
      }
    },
    "UpdateIncident": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Anterior": {
          "type": "string"
        },
        "Approximate_Patient_Age": {
          "type": "string"
        },
        "Date_of_Incident": {
          "type": "string"
        },
        "Gender": {
          "type": "string"
        },
        "ID": {
          "type": "string"
        },
        "Incident_Description": {
          "type": "string"
        },
        "Largest_Length": {
          "type": "string"
        },
        "Location_of_object": {
          "type": "string"
        },
        "Long-term_prognosis": {
          "type": "string"
        },
        "Object_Basic_Shape": {
          "type": "string"
        },
        "Object_Consistency": {
          "type": "string"
        },
        "The_object_is": {
          "type": "string"
        },
        "What_material_is_the_object_made_of": {
          "type": "string"
        }
      }
    },
    "UpdateIncidentGoodResponse": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Anterior": {
          "type": "string"
        },
        "Approximate_Patient_Age": {
          "type": "string"
        },
        "Date_of_Incident": {
          "type": "string"
        },
        "Gender": {
          "type": "string"
        },
        "ID": {
          "type": "string"
        },
        "Incident_Description": {
          "type": "string"
        },
        "Largest_Length": {
          "type": "string"
        },
        "Location_of_object": {
          "type": "string"
        },
        "Long-term_prognosis": {
          "type": "string"
        },
        "Object_Basic_Shape": {
          "type": "string"
        },
        "Object_Consistency": {
          "type": "string"
        },
        "The_object_is": {
          "type": "string"
        },
        "Updated": {
          "type": "boolean",
          "default": true
        },
        "What_material_is_the_object_made_of": {
          "type": "string"
        }
      }
    },
    "UpdateIncidentIncidentIdNotFoundResponse": {
      "type": "object",
      "required": [
        "ID"
      ],
      "properties": {
        "Anterior": {
          "type": "string"
        },
        "Approximate_Patient_Age": {
          "type": "string"
        },
        "Date_of_Incident": {
          "type": "string"
        },
        "Gender": {
          "type": "string"
        },
        "ID": {
          "type": "string"
        },
        "Incident_Description": {
          "type": "string"
        },
        "Largest_Length": {
          "type": "string"
        },
        "Location_of_object": {
          "type": "string"
        },
        "Long-term_prognosis": {
          "type": "string"
        },
        "Object_Basic_Shape": {
          "type": "string"
        },
        "Object_Consistency": {
          "type": "string"
        },
        "The_object_is": {
          "type": "string"
        },
        "Updated": {
          "type": "boolean",
          "default": false
        },
        "What_material_is_the_object_made_of": {
          "type": "string"
        }
      }
    },
    "UpdateUser": {
      "type": "object",
      "properties": {
        "degree": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "specialty": {
          "type": "string"
        }
      }
    },
    "UpdateUserGoodResponse": {
      "type": "object",
      "required": [
        "userId",
        "verified",
        "name",
        "degree",
        "updated",
        "email",
        "specialty"
      ],
      "properties": {
        "degree": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "specialty": {
          "type": "string"
        },
        "updated": {
          "type": "boolean"
        },
        "userId": {
          "type": "string"
        },
        "verified": {
          "type": "boolean",
          "default": false
        }
      }
    },
    "UpdateUserInvalidResponse": {
      "type": "object",
      "required": [
        "verified",
        "name",
        "degree",
        "specialty",
        "updated",
        "email"
      ],
      "properties": {
        "degree": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "specialty": {
          "type": "string"
        },
        "updated": {
          "type": "boolean",
          "example": false
        },
        "verified": {
          "type": "boolean",
          "example": false
        }
      }
    },
    "UpdateUserNotFoundResponse": {
      "type": "object",
      "required": [
        "userId"
      ],
      "properties": {
        "updated": {
          "type": "boolean",
          "default": false
        },
        "userId": {
          "type": "string"
        }
      }
    },
    "Verify": {
      "type": "object",
      "required": [
        "verified"
      ],
      "properties": {
        "verified": {
          "type": "boolean"
        }
      }
    }
  },
  "tags": [
    {
      "description": "to create, update, and delete incidents",
      "name": "incident"
    },
    {
      "description": "for user registration and authentication",
      "name": "user"
    },
    {
      "description": "only used for testing and will be removed in production",
      "name": "verify"
    }
  ]
}`))
}
