// Code generated by go-swagger; DO NOT EDIT.

package e_n_t_incident

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateENTIncidentHandlerFunc turns a function with the right signature into a create e n t incident handler
type CreateENTIncidentHandlerFunc func(CreateENTIncidentParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateENTIncidentHandlerFunc) Handle(params CreateENTIncidentParams) middleware.Responder {
	return fn(params)
}

// CreateENTIncidentHandler interface for that can handle valid create e n t incident params
type CreateENTIncidentHandler interface {
	Handle(CreateENTIncidentParams) middleware.Responder
}

// NewCreateENTIncident creates a new http.Handler for the create e n t incident operation
func NewCreateENTIncident(ctx *middleware.Context, handler CreateENTIncidentHandler) *CreateENTIncident {
	return &CreateENTIncident{Context: ctx, Handler: handler}
}

/* CreateENTIncident swagger:route POST /v3/entincident ENT Incident createENTIncident

create ENT Incident

Use this to delete an incident by incidentId

*/
type CreateENTIncident struct {
	Context *middleware.Context
	Handler CreateENTIncidentHandler
}

func (o *CreateENTIncident) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateENTIncidentParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
