// Code generated by go-swagger; DO NOT EDIT.

package e_n_t_incident

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gircapp/api/models"
)

// GetENTIncidentsOKCode is the HTTP code returned for type GetENTIncidentsOK
const GetENTIncidentsOKCode int = 200

/*GetENTIncidentsOK successful operation

swagger:response getENTIncidentsOK
*/
type GetENTIncidentsOK struct {

	/*
	  In: Body
	*/
	Payload *models.GetENTIncidentsGoodResponse `json:"body,omitempty"`
}

// NewGetENTIncidentsOK creates GetENTIncidentsOK with default headers values
func NewGetENTIncidentsOK() *GetENTIncidentsOK {

	return &GetENTIncidentsOK{}
}

// WithPayload adds the payload to the get e n t incidents o k response
func (o *GetENTIncidentsOK) WithPayload(payload *models.GetENTIncidentsGoodResponse) *GetENTIncidentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get e n t incidents o k response
func (o *GetENTIncidentsOK) SetPayload(payload *models.GetENTIncidentsGoodResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetENTIncidentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
