// Code generated by go-swagger; DO NOT EDIT.

package e_n_t_incident

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gircapp/api/models"
)

// UpdateENTIncidentOKCode is the HTTP code returned for type UpdateENTIncidentOK
const UpdateENTIncidentOKCode int = 200

/*UpdateENTIncidentOK successful operation

swagger:response updateENTIncidentOK
*/
type UpdateENTIncidentOK struct {

	/*
	  In: Body
	*/
	Payload *models.GoodResponse `json:"body,omitempty"`
}

// NewUpdateENTIncidentOK creates UpdateENTIncidentOK with default headers values
func NewUpdateENTIncidentOK() *UpdateENTIncidentOK {

	return &UpdateENTIncidentOK{}
}

// WithPayload adds the payload to the update e n t incident o k response
func (o *UpdateENTIncidentOK) WithPayload(payload *models.GoodResponse) *UpdateENTIncidentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update e n t incident o k response
func (o *UpdateENTIncidentOK) SetPayload(payload *models.GoodResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateENTIncidentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
