// Code generated by go-swagger; DO NOT EDIT.

package medical_expert

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetExpertHandlerFunc turns a function with the right signature into a get expert handler
type GetExpertHandlerFunc func(GetExpertParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetExpertHandlerFunc) Handle(params GetExpertParams) middleware.Responder {
	return fn(params)
}

// GetExpertHandler interface for that can handle valid get expert params
type GetExpertHandler interface {
	Handle(GetExpertParams) middleware.Responder
}

// NewGetExpert creates a new http.Handler for the get expert operation
func NewGetExpert(ctx *middleware.Context, handler GetExpertHandler) *GetExpert {
	return &GetExpert{Context: ctx, Handler: handler}
}

/* GetExpert swagger:route GET /v3/expert Medical Expert getExpert

register expert

Use this to register a expert

*/
type GetExpert struct {
	Context *middleware.Context
	Handler GetExpertHandler
}

func (o *GetExpert) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetExpertParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
