// Code generated by go-swagger; DO NOT EDIT.

package incident

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/gircapp/api/swagger/models"
)

// CreateIncidentOKCode is the HTTP code returned for type CreateIncidentOK
const CreateIncidentOKCode int = 200

/*CreateIncidentOK successful operation, only returns token if not using OAuth

swagger:response createIncidentOK
*/
type CreateIncidentOK struct {
	/*token

	 */
	Authentication string `json:"Authentication"`

	/*
	  In: Body
	*/
	Payload *models.CreateIncidentGoodResponse `json:"body,omitempty"`
}

// NewCreateIncidentOK creates CreateIncidentOK with default headers values
func NewCreateIncidentOK() *CreateIncidentOK {

	return &CreateIncidentOK{}
}

// WithAuthentication adds the authentication to the create incident o k response
func (o *CreateIncidentOK) WithAuthentication(authentication string) *CreateIncidentOK {
	o.Authentication = authentication
	return o
}

// SetAuthentication sets the authentication to the create incident o k response
func (o *CreateIncidentOK) SetAuthentication(authentication string) {
	o.Authentication = authentication
}

// WithPayload adds the payload to the create incident o k response
func (o *CreateIncidentOK) WithPayload(payload *models.CreateIncidentGoodResponse) *CreateIncidentOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create incident o k response
func (o *CreateIncidentOK) SetPayload(payload *models.CreateIncidentGoodResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateIncidentOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header Authentication

	authentication := o.Authentication
	if authentication != "" {
		rw.Header().Set("Authentication", authentication)
	}

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateIncidentUnauthorizedCode is the HTTP code returned for type CreateIncidentUnauthorized
const CreateIncidentUnauthorizedCode int = 401

/*CreateIncidentUnauthorized bNews and buzzad authorization token

swagger:response createIncidentUnauthorized
*/
type CreateIncidentUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.CreateIncidentInvalidIncidentResponse `json:"body,omitempty"`
}

// NewCreateIncidentUnauthorized creates CreateIncidentUnauthorized with default headers values
func NewCreateIncidentUnauthorized() *CreateIncidentUnauthorized {

	return &CreateIncidentUnauthorized{}
}

// WithPayload adds the payload to the create incident unauthorized response
func (o *CreateIncidentUnauthorized) WithPayload(payload *models.CreateIncidentInvalidIncidentResponse) *CreateIncidentUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create incident unauthorized response
func (o *CreateIncidentUnauthorized) SetPayload(payload *models.CreateIncidentInvalidIncidentResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateIncidentUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreateIncidentNotFoundCode is the HTTP code returned for type CreateIncidentNotFound
const CreateIncidentNotFoundCode int = 404

/*CreateIncidentNotFound userId for this incident is not found

swagger:response createIncidentNotFound
*/
type CreateIncidentNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.CreateIncidentUserIDNotFoundResponse `json:"body,omitempty"`
}

// NewCreateIncidentNotFound creates CreateIncidentNotFound with default headers values
func NewCreateIncidentNotFound() *CreateIncidentNotFound {

	return &CreateIncidentNotFound{}
}

// WithPayload adds the payload to the create incident not found response
func (o *CreateIncidentNotFound) WithPayload(payload *models.CreateIncidentUserIDNotFoundResponse) *CreateIncidentNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create incident not found response
func (o *CreateIncidentNotFound) SetPayload(payload *models.CreateIncidentUserIDNotFoundResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateIncidentNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
