// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Ban ban
//
// swagger:model Ban
type Ban struct {

	// banned
	// Required: true
	Banned *bool `json:"banned"`
}

// Validate validates this ban
func (m *Ban) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBanned(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Ban) validateBanned(formats strfmt.Registry) error {

	if err := validate.Required("banned", "body", m.Banned); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this ban based on context it is used
func (m *Ban) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Ban) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Ban) UnmarshalBinary(b []byte) error {
	var res Ban
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
