// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateSwallowedObject create swallowed object
//
// swagger:model CreateSwallowedObject
type CreateSwallowedObject struct {

	// anterior image
	AnteriorImage string `json:"AnteriorImage,omitempty"`

	// consistency
	Consistency string `json:"Consistency,omitempty"`

	// custom materials
	CustomMaterials []string `json:"CustomMaterials"`

	// custom shape
	CustomShape string `json:"CustomShape,omitempty"`

	// ID
	ID string `json:"ID,omitempty"`

	// incident ID
	IncidentID string `json:"IncidentID,omitempty"`

	// laterial image
	LaterialImage string `json:"LaterialImage,omitempty"`

	// location
	Location int64 `json:"Location,omitempty"`

	// materials
	Materials []int64 `json:"Materials"`

	// posterior image
	PosteriorImage string `json:"PosteriorImage,omitempty"`

	// removal difficulty
	RemovalDifficulty int64 `json:"RemovalDifficulty,omitempty"`

	// shape
	Shape int64 `json:"Shape,omitempty"`
}

// Validate validates this create swallowed object
func (m *CreateSwallowedObject) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create swallowed object based on context it is used
func (m *CreateSwallowedObject) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateSwallowedObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateSwallowedObject) UnmarshalBinary(b []byte) error {
	var res CreateSwallowedObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
