// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeleteENTIncident delete e n t incident
//
// swagger:model DeleteENTIncident
type DeleteENTIncident struct {

	// e n t incident ID
	// Required: true
	ENTIncidentID *string `json:"ENTIncidentID"`
}

// Validate validates this delete e n t incident
func (m *DeleteENTIncident) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateENTIncidentID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeleteENTIncident) validateENTIncidentID(formats strfmt.Registry) error {

	if err := validate.Required("ENTIncidentID", "body", m.ENTIncidentID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete e n t incident based on context it is used
func (m *DeleteENTIncident) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteENTIncident) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteENTIncident) UnmarshalBinary(b []byte) error {
	var res DeleteENTIncident
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
