// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DeleteSwallowedObject delete swallowed object
//
// swagger:model DeleteSwallowedObject
type DeleteSwallowedObject struct {

	// swallowed object ID
	// Required: true
	SwallowedObjectID *string `json:"SwallowedObjectID"`
}

// Validate validates this delete swallowed object
func (m *DeleteSwallowedObject) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSwallowedObjectID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DeleteSwallowedObject) validateSwallowedObjectID(formats strfmt.Registry) error {

	if err := validate.Required("SwallowedObjectID", "body", m.SwallowedObjectID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this delete swallowed object based on context it is used
func (m *DeleteSwallowedObject) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DeleteSwallowedObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DeleteSwallowedObject) UnmarshalBinary(b []byte) error {
	var res DeleteSwallowedObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
