// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetExpertResponse get expert response
//
// swagger:model GetExpertResponse
type GetExpertResponse struct {

	// degree
	Degree string `json:"Degree,omitempty"`

	// director verified
	DirectorVerified bool `json:"DirectorVerified,omitempty"`

	// email
	Email string `json:"Email,omitempty"`

	// expertise
	Expertise string `json:"Expertise,omitempty"`

	// ID
	ID string `json:"ID,omitempty"`

	// name
	Name string `json:"Name,omitempty"`
}

// Validate validates this get expert response
func (m *GetExpertResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this get expert response based on context it is used
func (m *GetExpertResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetExpertResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetExpertResponse) UnmarshalBinary(b []byte) error {
	var res GetExpertResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
