// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SwallowedObject swallowed object
//
// swagger:model SwallowedObject
type SwallowedObject struct {

	// anterior photo
	AnteriorPhoto string `json:"AnteriorPhoto,omitempty"`

	// consistency
	Consistency string `json:"Consistency,omitempty"`

	// custom materials
	CustomMaterials []string `json:"CustomMaterials"`

	// custom shape
	CustomShape string `json:"CustomShape,omitempty"`

	// laterial photo
	LaterialPhoto string `json:"LaterialPhoto,omitempty"`

	// location
	Location int64 `json:"Location,omitempty"`

	// longest depth
	LongestDepth float64 `json:"LongestDepth,omitempty"`

	// longest height
	LongestHeight float64 `json:"LongestHeight,omitempty"`

	// longest width
	LongestWidth float64 `json:"LongestWidth,omitempty"`

	// materials
	Materials []int64 `json:"Materials"`

	// posterior photo
	PosteriorPhoto string `json:"PosteriorPhoto,omitempty"`

	// removal difficulty
	RemovalDifficulty int64 `json:"RemovalDifficulty,omitempty"`

	// shape
	Shape int64 `json:"Shape,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// incident ID
	IncidentID string `json:"incidentID,omitempty"`
}

// Validate validates this swallowed object
func (m *SwallowedObject) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this swallowed object based on context it is used
func (m *SwallowedObject) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SwallowedObject) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SwallowedObject) UnmarshalBinary(b []byte) error {
	var res SwallowedObject
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
